### ISSUE TITLE
add seasons to the game

### ISSUE THREAD

**Issue by cblgh** [XXIIVV/Blind#10]
i.e. leaderboards are for a limited amount of time, one season. this makes it easier and more pleasant for new players to get into the game.

also, maybe add an archive to save the history of how previous seasons turned out

finally, maybe create a name generator for each season to add some flavor?

**Comment by neauoire** [comment]
EEEEEEEHH!!
Brilliant! 
YES!

**Comment by maxdeviant** [comment]
:+1:

**Comment by neauoire** [comment]
Added!
