### ISSUE TITLE
Unresponsiveness on Chrome

### ISSUE THREAD

**Issue by johnakers** [XXIIVV/Blind#16]
Clicking `Respawn` to start the game does nothing but does create JS errors in Chrome.

_gif below shows what I'm encountering_

![blindfolk](http://i.imgur.com/45S0KXg.gif)

**Comment by neauoire** [comment]
There seems to be a problem with a few players using Chrome.
I haven't found the issue yet, as I cannot reproduce it.

**Comment by maxdeviant** [comment]
Issue is on [line 141 in script.js](https://github.com/XXIIVV/Blind/blob/master/inc/script.js#L141).

Looks like `leaderboard.player` is undefined.

**Comment by neauoire** [comment]
Fixed :)
