### ISSUE TITLE
Attack riposte always ends deadly

### ISSUE THREAD

**Issue by voidshaper777** [XXIIVV/Blind#18]
Previously, a case attack.forward or .backward would prevent a kill from the attack command that triggered it. Now, after the case has resolved, the player dies. Is this expected behavior?
![example](https://cloud.githubusercontent.com/assets/17031485/12801165/bc76a5b8-cada-11e5-80ae-f86e55db71a5.JPG)

**Comment by amatecha** [comment]
happened to me too
`79 kills 2.`
`79 says "xopa".`
`2 kills 79.`

**Comment by neauoire** [comment]
Fixed :)
