### ISSUE TITLE
Add a visible caret in # FIGHTING STYLE section

### ISSUE THREAD

**Issue by mothnode** [XXIIVV/Blind#20]
Not sure if it's just me but when I type anything in latest Chrome the caret doesn't appear at all, leaving the player guessing where the was the last selection to start typing.

**Comment by neauoire** [comment]
Duplicate to https://github.com/XXIIVV/Blind/issues/12

**Comment by mothnode** [comment]
Ah right, yeah. Sorry about that ;)
