### ISSUE TITLE
Add strategic element

### ISSUE THREAD

**Issue by voidshaper777** [XXIIVV/Blind#3]
I found that one can arrive quickly at effective tactics, and mostly only adjusts the start/default loop to the actions of the other players. By adding a strategic element, the tactics could be more varied. For example, players can choose a single perk that sets out the strategic approach:
Agile -> Players get an exclusive phase every nth phase
Endurance -> Players get a small bonus on their stamina
Combatant -> Unlocks attack.left, attack.right commands and cases
etc.

**Comment by neauoire** [comment]
I think for now, that might complexity a bit too much.
I will see what I can do!
