### ISSUE TITLE
Starting positions of players

### ISSUE THREAD

**Issue by voidshaper777** [XXIIVV/Blind#4]
Having all players spawn at (0,0) creates some issues, especially with many players. For example:
Player 1 goes first, moves backward (0, -1)
Player 2 attacks backward
Player 1 attack.forward case triggers. She circle strafes the starting point to (-1, 0) and attacks (because the script is resolved instantly, she can perform three operations)
Player 3 is killed by the attack instead of Player 1, because of the way the code handles the stack of players on (0,0) - that's a bit unfair for Player 3 imo

Giving the players random starting positions and orientations in the room could force more variance in the scripts.

**Comment by neauoire** [comment]
It will make it harder to devise strategies and make the game more random than it already is, no?

**Comment by voidshaper777** [comment]
Yeah, I wasn't too sure to even submit this one. It was just something I noticed and thought I'd mention it.

**Comment by neauoire** [comment]
Maybe I can make arenas at some point, or labyrinths like Osavox suggested.

**Comment by mothnode** [comment]
Arenas/labyrinths sound great, yeah.
