### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by jackaperkins** [XXIIVV/Blind#5]
Bug report on osx 10.10,  chrome Version 48.0.2564.97 

```
Uncaught SyntaxError: Unexpected token <   VM151:1
Uncaught TypeError: Cannot read property 'rank' of undefined script.js:141
```

Hey, getting these errors on loading the game. Pressing the 'respawn' link causes output of them again each time. Write a script and tried to save it, but saving sticks at some % and never finishes.

**Comment by jackaperkins** [comment]
Works fine for me in Safari though!

**Comment by neauoire** [comment]
Could you try deleting the "token" cookie? Let me know if that fixes it.

**Comment by jackaperkins** [comment]
Hmm, deleted and refreshed the page and got:

```
Uncaught TypeError: Cannot read property 'id' of null     VM302:1
Uncaught TypeError: Cannot read property 'rank' of undefined   Script.js:141
```

After that, refreshing the page just returns to the first errors.

**Comment by neauoire** [comment]
I will investigate.
I just got DDoS pretty badly today, I will resume work on Blind tomorrow.

**Comment by maxdeviant** [comment]
Seems like this is related to #16 .

**Comment by neauoire** [comment]
Fixed :)

**Comment by jackaperkins** [comment]
Gulp, I deleted cookies and tried again on chrome. Now I get this:
<img width="1070" alt="screen shot 2016-02-03 at 4 53 19 pm" src="https://cloud.githubusercontent.com/assets/540820/12802171/c315e062-ca96-11e5-9f0b-390936584506.png">
Could this be because I already have a token (player #146) on my Safari side?

**Comment by neauoire** [comment]
try again? I think I figured it out.

**Comment by jackaperkins** [comment]
:+1: A-OK

**Comment by maxdeviant** [comment]
Ayyyyyyyyy :fireworks:
