### ISSUE TITLE
Multiple kills of same Blindfolk

### ISSUE THREAD

**Issue by voidshaper777** [XXIIVV/Blind#6]
This seems to happen when more than one ripostes occur (ie. recursion depth >1):
257 collides with 292
257 "case collide.right" triggers
turns right, attacks 292  --> first attack is on layer 1 of the recursive function
292 counter attacks
257 "case attack.forward" triggers
257 moves, attacks 292 --> second attack is on layer 2 of the recursive function
257 kills 292 <-- layer 2 attack resolves
257 kills 292 <-- layer 1 attack resolves
![blindfolk](https://cloud.githubusercontent.com/assets/17031485/12786698/7fa05eba-ca92-11e5-9e8d-aaf725ca0351.PNG)

**Comment by voidshaper777** [comment]
Should be fixable by checking if target != dead in
182       if target && target.x == new_x && target.y == new_y

edit: sorry for closing & opening again, I'm a github noob

**Comment by neauoire** [comment]
Fixed!
